Sprint 8
katesim/java-filmorate pull request #1
Opened 2022-08-03 02:15 UTC by katesim

Создан каркас Spring Boot приложения Filmorate.

Добавлены модели Film и User и ручки для их создания, обновления, чтения.
Тесты для валидации данных.

2022-08-03 16:52 UTC, kukolev requested changes

2022-08-03 16:52 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/controller/FilmController.java
> +        log.info("Фильм с id=" + film.getId() + "создан");
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)` или `log.warn(String.format("Some warning text for %s", val))` . Так код смотрится проще и тратится меньше ресурсов.

Аналогично нужно поправить в остальных местах кода, где есть логирование.

2022-08-03 16:52 UTC, kukolev commented on src/test/java/ru/com/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-08-03 17:53 UTC, katesim commented on src/main/java/ru/com/practicum/filmorate/controller/FilmController.java
> +        log.info("Фильм с id=" + film.getId() + "создан");
Исправлено.

2022-08-03 17:54 UTC, katesim commented on src/test/java/ru/com/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Исправлено.

2022-08-04 17:06 UTC, kukolev requested changes

2022-08-04 17:06 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/validator/UserValidator.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Это уже часть логики приложения, а не валидация. Валидация подразумевает проверку данных и выброс эксепшенов, а не модификацию объекта. Это логичней перенести в сервис.

2022-08-05 05:09 UTC, katesim commented on src/main/java/ru/com/practicum/filmorate/validator/UserValidator.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Перенесла в `UserController`, тк добавление сервисов относится уже к следующему спринту.

2022-08-06 11:26 UTC, kukolev approved these changes

2022-08-09 00:45 UTC, merged