Sprint 12 / add directors and reviews, search, recommendations, feed
katesim/java-filmorate pull request #17
Opened 2022-08-25 21:28 UTC by katesim

Добавлены:
- Сущность для режиссеров
- Поиск по названию фильмов и по режиссёру 
- Отзывы к фильмам
- Рекомендации фильмов пользователю
- Лента событий
- Вывод самых популярных фильмов по жанру и годам
- Вывод общих с другом фильмов с сортировкой по их популярности
- Удаление фильмов и пользователей

2022-08-26 15:54 UTC, kukolev requested changes

2022-08-26 15:54 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/controller/ReviewController.java
> +        if (filmId == null) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-26 15:54 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/controller/UserController.java
>          userService.makeFriends(id, friendId);
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-26 15:54 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/model/SortingTypes.java
> +    year, likes
Нарушение кодстайла: енумы принято делать в верхнем регистре.

2022-08-26 15:54 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/storage/film/DBFilmStorage.java
> +    private Film makeFilm(ResultSet rs, GenreService genreService, DirectorService directorService) throws SQLException {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-08-26 16:23 UTC, katesim commented on src/main/java/ru/com/practicum/filmorate/controller/UserController.java
>          userService.makeFriends(id, friendId);
О какой бизнес-логике здесь идет речь?

2022-08-26 16:29 UTC, katesim commented on src/main/java/ru/com/practicum/filmorate/model/SortingTypes.java
> +    year, likes
@kukolev как [здесь](https://github.com/katesim/java-filmorate/blob/develop/src/main/java/ru/com/practicum/filmorate/controller/FilmController.java#L91) замапить параметр `sortBy` в нижнем регистре на этот enum?

2022-08-26 21:14 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/controller/UserController.java
>          userService.makeFriends(id, friendId);
Здесь выполняется три действия - добавляется друг, создается ивент и этот ивент добавляется в сервис. Это и есть логика. Эту логику нужно инкапсулировать в сервис.

2022-08-26 21:14 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/model/SortingTypes.java
> +    year, likes
По моему вопросу уже не актуален - получилось вполне корректно. Можно еще сделать по другому - добавить в енум приватное поле и мапить на него. Но текущий вариант тоже хороший, переделывать не нужно.

2022-08-27 07:12 UTC, kukolev requested changes

2022-08-27 07:12 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/controller/FilmController.java
> +        Event event = Event.builder()
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-27 07:12 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/controller/ReviewController.java
> +        Event event = Event.builder()
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-27 07:12 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/validator/DirectorValidator.java
> +@Slf4j
Эта аннотация тут не нужна, т.к. нет логов. Нужно убрать аннотацию или добавить логи.

2022-08-27 07:12 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/controller/FilmController.java
>  @Slf4j
Эта аннотация тут не нужна, т.к. нет логов. Нужно убрать аннотацию или добавить логи.

2022-08-27 07:12 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/controller/UserController.java
>  @Slf4j
Эта аннотация тут не нужна, т.к. нет логов. Нужно убрать аннотацию или добавить логи.

2022-08-27 07:12 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/service/DirectorService.java
> +@Slf4j
Эта аннотация тут не нужна, т.к. нет логов. Нужно убрать аннотацию или добавить логи.

2022-08-27 07:12 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/storage/director/DBDirectorStorage.java
> +@Slf4j
Эта аннотация тут не нужна, т.к. нет логов. Нужно убрать аннотацию или добавить логи.

2022-08-27 07:12 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/model/Film.java
> +    private List<Director> directors;
Лучше сделать это поле инициализированным по умолчанию. Тогда не придется писать проверку на null по всему коду. Как правило считается хорошим тоном сделать пустую коллекцию, а не null.

Аналогичное касается и поля genres выше.

2022-08-27 07:12 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/storage/film/DBFilmStorage.java
> +    public List<Film> searchFilms(String directorSubstring, String titleSubstring) {
Подход по использованию этого метода лучше сменить, добавив второй вариант с одним параметром. Дело в том, что один из вызовов метода происходит с одинаковыми параметрами. Получается, что код два раза выполняет одинаковые преобразования. Это с одной стороны не большая проблема. С другой стороны подобные странности говорят о проблемах в дизайне. Думаю стоит это как-то поправить.

2022-08-27 07:12 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/service/FilmService.java
> +    public List<Film> searchFilms(String query, String by) {
Этот метод сейчас вполне рабочий, но нерасширяемый. Если добавятся новые поля для поиска, то варианты в switch будут расти нелинейно. По моему лучше было бы реализовать конструктор запросов - если в строке есть "director", то добавляем логику фильтрации по директору, если title, то добавляем логику поиска по title и т.п.

2022-09-01 18:21 UTC, alex1261bat commented on src/main/java/ru/com/practicum/filmorate/controller/ReviewController.java
> +        if (filmId == null) {
Перенесено в сервис. Здесь оставлен вызов метода сервиса.

2022-09-01 18:21 UTC, alex1261bat commented on src/main/java/ru/com/practicum/filmorate/controller/UserController.java
>          userService.makeFriends(id, friendId);
Перенесено в сервис.

2022-09-01 18:22 UTC, alex1261bat commented on src/main/java/ru/com/practicum/filmorate/controller/ReviewController.java
> +        Event event = Event.builder()
Перенесено в сервис.

2022-09-01 18:22 UTC, alex1261bat commented on src/main/java/ru/com/practicum/filmorate/validator/DirectorValidator.java
> +@Slf4j
Убрана аннотация.

2022-09-01 18:23 UTC, alex1261bat commented on src/main/java/ru/com/practicum/filmorate/controller/UserController.java
>  @Slf4j
Убрана аннотация.

2022-09-01 18:23 UTC, alex1261bat commented on src/main/java/ru/com/practicum/filmorate/service/DirectorService.java
> +@Slf4j
Убрана аннотация.

2022-09-01 18:23 UTC, alex1261bat commented on src/main/java/ru/com/practicum/filmorate/storage/director/DBDirectorStorage.java
> +@Slf4j
Убрана аннотация.

2022-09-01 18:24 UTC, alex1261bat commented on src/main/java/ru/com/practicum/filmorate/model/Film.java
> +    private List<Director> directors;
Поле помечено final и проинициализировано.

2022-09-01 18:24 UTC, anzerdev commented on src/main/java/ru/com/practicum/filmorate/storage/film/DBFilmStorage.java
> +    public List<Film> searchFilms(String directorSubstring, String titleSubstring) {
Ксения исправила.

2022-09-01 18:25 UTC, alex1261bat commented on src/main/java/ru/com/practicum/filmorate/service/FilmService.java
> +    public List<Film> searchFilms(String query, String by) {
Ксения исправила.

2022-09-02 06:30 UTC, kukolev approved these changes

2022-09-08 22:43 UTC, merged