Sprint 9
katesim/java-filmorate pull request #4
Opened 2022-08-14 01:09 UTC by katesim

2022-08-14 09:03 UTC, kukolev requested changes

2022-08-14 09:03 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
По условиям ТЗ контроллеры должны зависеть только от сервисов. Хранилища должны быть внедрены в сервисы. Это позволяет логически отделить слой API от слоя бизнес-логики.

2022-08-14 09:03 UTC, kukolev commented on src/main/java/ru/com/practicum/filmorate/controller/FilmController.java
>          FilmValidator.validate(film);
Валидация это тоже часть бизнес логики, место которой в сервисе. Нужно перенести вызов метода валидации в сервис.

2022-08-14 15:02 UTC, katesim commented on src/main/java/ru/com/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
исправлено, спасибо!

2022-08-14 15:03 UTC, katesim commented on src/main/java/ru/com/practicum/filmorate/controller/FilmController.java
>          FilmValidator.validate(film);
замечание исправлено

2022-08-15 07:19 UTC, kukolev approved these changes

2022-08-15 16:30 UTC, merged